#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      vue-deps:
        patterns:
          - "vue*"
          - "@vue*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
